# Generated by Django 4.2.2 on 2023-09-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
